spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    show-sql: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/expense
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.internal/realms/uptimecrew
cache:
  type: redis
  redis:
    time-to-live: 60000
    cache-null-values: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
